# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anxiety Dog Comic
author: Gretchen Kisler
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Life is a little more difficult when you're afraid of going through doors.


  Despite his fear of just about everything, Billy was (and continues to be) pretty smart and inquisitive. He is a natural athlete. His favorite thing is running on the beach, and rock climbing like a ninja. He is a pretty happy little guy with the occasional flare ups of crippling anxiety, but these get easier as time goes on.


  Billy began his life as a pound puppy, and had only been in a foster home for about a month when we met him. We took him home that day. It became very quickly apparent that he was going to need some extra attention. He was too afraid to go in through the front door, and only slightly less terrified of the back door, so I sat outside with him for four hours (yup, four) until he was comfortable enough to go inside. At that point, he had decided we were best friends.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anxietydogcomic.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
feed:
  path: rss

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
